USE [master]
GO
/****** Object:  Database [GunManagement]    Script Date: 5/7/2013 12:55:13 PM ******/
CREATE DATABASE [GunManagement] ON  PRIMARY 
( NAME = N'GunManagement', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\GunManagement.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GunManagement_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\GunManagement_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [GunManagement] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GunManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GunManagement] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GunManagement] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GunManagement] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GunManagement] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GunManagement] SET ARITHABORT OFF 
GO
ALTER DATABASE [GunManagement] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GunManagement] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [GunManagement] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GunManagement] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GunManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GunManagement] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GunManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GunManagement] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GunManagement] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GunManagement] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GunManagement] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GunManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GunManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GunManagement] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GunManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GunManagement] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GunManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GunManagement] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GunManagement] SET RECOVERY FULL 
GO
ALTER DATABASE [GunManagement] SET  MULTI_USER 
GO
ALTER DATABASE [GunManagement] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GunManagement] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'GunManagement', N'ON'
GO
ALTER DATABASE [GunManagement] SET  READ_WRITE 
GO
